version: '2'
services:
    demo-app:
        image: demo
        external_links:
            - demo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/demo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - GOOGLEAPIKEY # this value needs to be passed via an environment variable
            - DARKSKYAPIKEY # this value needs to be passed via an environment variable
            - BIOGRAPHIESREMOTELOCATION # this value needs to be passed via an environment variable
        ports:
            # let's make sure we are not confused in development between docker and direct jvm launching
            - 9000:8080
    demo-postgresql:
        extends:
            file: postgresql.yml
            service: demo-postgresql
