version: '2'
services:
    demo-app:
        image: demo
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://demo-mysql:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - JHIPSTER_CACHE_EHCACHE_CLUSTER_URI=terracotta://terracotta-server1:9410,terracotta-server2:9410/demo-entity
            - DEMO_STUBWEBSERVICES=false
            - DEMO_GOOGLEAPIKEY # this value needs to be passed via an environment variable
            - DEMO_DARKSKYAPIKEY # this value needs to be passed via an environment variable
            - DEMO_BIOGRAPHIESREMOTELOCATION # this value needs to be passed via an environment variable
        ports:
            - 8080:8080
    demo-mysql:
        extends:
            file: mysql.yml
            service: demo-mysql
    demo-terracotta-server1:
        extends:
            file: terracotta-server.yml
            service: demo-terracotta-server1
    demo-terracotta-server2:
        extends:
            file: terracotta-server.yml
            service: demo-terracotta-server2
