version: '2'
services:
    demo-terracotta-server1:
        container_name: demo-terracotta-server1
        image: anthonydahanne/terracotta-server-oss:5.1.0_AP
        environment:
            - OFFHEAP_RESOURCE_SIZE=256
            - OFFHEAP_RESOURCE_UNIT=MB
            - OFFHEAP_RESOURCE_NAME=primary-server-resource
            - TC_SERVER1=demo-terracotta-server1
            - TC_SERVER2=demo-terracotta-server2
        ports:
            - 9510
    demo-terracotta-server2:
        container_name: demo-terracotta-server2
        image: anthonydahanne/terracotta-server-oss:5.1.0_AP
        environment:
            - OFFHEAP_RESOURCE_SIZE=256
            - OFFHEAP_RESOURCE_UNIT=MB
            - OFFHEAP_RESOURCE_NAME=primary-server-resource
            - TC_SERVER1=demo-terracotta-server1
            - TC_SERVER2=demo-terracotta-server2
        ports:
            - 9510
